### ISSUE TITLE
There was a problem with the same name of the file to replace the file in a different path

### ISSUE THREAD

**Issue by cloudyan** [wpfpizicai/gulp-md5-plus#8]
hi，

I really like this plugin, great resolve caching issues，but there was a problem with the same name of the file to replace the file in a different path, E.g:

<pre>
&lt;link rel="stylesheet" href="__DOMAIN__static/boss/css/colors/dwd.css"&gt;
&lt;link rel="stylesheet" href="__DOMAIN__static/css/dwd.css"&gt;
</pre>

When replace the file name, if the ratio of the path, I can solve this problem, Add path `sub_namepath`

<pre>
if(Object.prototype.toString.call(ifile) == "[object Array]"){
    ifile.forEach(function(i_ifile){
        i_ifile && glob(i_ifile,function(err, i_files){
            if(err) return console.log(err);
            i_files.forEach(function(i_ilist){
                var result = fs.readFileSync(i_ilist,'utf8').replace(new RegExp(sub_namepath + filename + '[^a-zA-Z_0-9].*?' ,"g"), function(sfile_name){
                return sfile_name.replace(sub_namepath + filename,sub_namepath + md5_filename)
            });
                fs.writeFileSync(i_ilist, result, 'utf8');
            })
        })
    })
}else{
    ifile && glob(ifile,function(err, files){
        if(err) return console.log(err);
        files.forEach(function(ilist){
            var result = fs.readFileSync(ilist,'utf8').replace(new RegExp(sub_namepath + filename + '[^a-zA-Z_0-9].*?' ,"g"), function(sfile_name){
                return sfile_name.replace(sub_namepath + filename,sub_namepath + md5_filename)
            });
            fs.writeFileSync(ilist, result, 'utf8');
        })
    })
}
</pre>

Can you update about what plug-ins, in order to support this demand, thankyou

**Comment by wpfpizicai** [comment]
I will refactor this plugin ; you can pull request or change the filename to fix your problem temporarily！

**Comment by wpfpizicai** [comment]
@cloudyan I have fixed this problem ,you can update the plugin to 0.2.4; if you have any other questions pls feel free to new issue.

**Comment by cloudyan** [comment]
@wpfpizicai this problem is unfixed，still have a little problem. different path and different file,but replaced as a last file

<pre>
&lt;link rel="icon" type="image/png" href="//static.doweidu.com/static/iqg/favicon_9d14bbe40c.png"&gt;
&lt;link rel="icon" type="image/png" href="//static.doweidu.com/static/hsq/favicon_9d14bbe40c.png"&gt;
</pre>

should be

<pre>
&lt;link rel="icon" type="image/png" href="//static.doweidu.com/static/iqg/favicon_01113cdd06.png"&gt;
&lt;link rel="icon" type="image/png" href="//static.doweidu.com/static/hsq/favicon_9d14bbe40c.png"&gt;
</pre>
